// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://your-project.supabase.co'
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'your-anon-key'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Server-side client for API routes
export const createServerClient = () => {
  return createClient(
    import.meta.env.VITE_SUPABASE_URL || 'https://your-project.supabase.co',
    import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY || 'your-service-role-key'
  )
}